citnames: include fmt/ranges.h for using fmt::join()
fmt::join() was moved into fmt/ranges.h since fmt v11, so include
this header for using fmt::join(). otherwise, we'd have following
compilation failure when building Bear with fmt v11 and up:

```
/builddir/build/BUILD/bear-3.1.4-build/Bear-3.1.4/source/citnames/source/semantic/Parsers.h:255:73: error: ‘join’ is not a member of ‘fmt’
  255 |                             fmt::format("Failed to recognize: {}", fmt::join(remainder.begin(), remainder.end(), ", "))
      |                                                                         ^~~~
```

Signed-off-by: Kefu Chai <tchaikov@gmail.com>